[package]
name = "rust-anticaptcha"
version = "0.0.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.11", features = ["json"] }
serde_json = "1.0.134"
tokio = { version = "1.21.2", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }

