name: Build Doc

on:
  push:
    branches: [ "master"]
    paths:
      - '.github/workflows/build_doc.yml'
      - 'src/**'
      - 'Cargo.toml'
  pull_request:
    branches: [ "master", "release"]
    paths:
      - '.github/workflows/build_doc.yml'
      - 'src/**'
      - 'Cargo.toml'
  schedule:
    - cron: "5 0 * * 1"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build doc
      run: cargo doc --verbose
