name: Clippy

on:
  push:
    branches: [ "master"]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'tests/**'
      - 'Cargo.toml'
  pull_request:
    branches: [ "master", "release"]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'tests/**'
      - 'Cargo.toml'
  schedule:
    - cron: "5 0 * * 1"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy --verbose
